// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

dotenv.config({ path: ".env.local" });

const pw = process.env["VITE_SUPABASE_PASSWORD"]
const connectionString = process.env["VITE_SUPABASE_CONNECTION_STRING"];

if (!connectionString || !pw) {
  console.error('Connection string or Password is missing');
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations"
  },
  datasource: {
    url: connectionString?.replace('[YOUR-PASSWORD]', pw ?? '')
  }
});
