#!/bin/bash

# Create a simple blue square PNG for icon16 (base64 encoded minimal PNG)
echo "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAKElEQVR42mNgGAWjYBSMAjSQnp7+n4GBgRENUMUYRsEoGAWjYBQAAKlNA9/1TbixAAAAAElFTkSuQmCC" | base64 -d > icon16.png

# Create icon48
echo "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAARklEQVR42u3OMQ0AAAgDsM6/aIMPJXCZ0QQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgBj1oAOftNOeMAAAAASUVORK5CYII=" | base64 -d > icon48.png

# Create icon128
echo "iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAAiElEQVR42u3OMQ0AAAjAMPC/aIMPJXCZQQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AjcUAAkPHgGsAAAAASUVORK5CYII=" | base64 -d > icon128.png

echo "Basic PNG icons created!"
ls -lh *.png
